bases:
- ../environments.yaml
helmDefaults:
  atomic: true
  devel: false
  force: false
  recreatePods: false
  tillerless: false
  timeout: 520
  tls: false
  verify: false
  wait: true
releases:
- chart: stable/velero
  name: velero
  namespace: foo
  needs:
  - jx/namespace-foo
  values:
  - test_data/jenkins-x-versions/apps/stable/velero/values.yaml.gotmpl
  - ../jx-requirements.values.yaml.gotmpl
  version: 2.7.4
- chart: zloeber/namespace
  name: namespace-foo
  namespace: jx
  values:
  - generated/foo/values.yaml
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: zloeber
  url: git+https://github.com/rawlingsj/helm-namespace@chart
