bases:
- ../environments.yaml
helmDefaults:
  atomic: true
  devel: false
  force: false
  recreatePods: false
  tillerless: false
  timeout: 520
  tls: false
  verify: false
  wait: true
releases:
- chart: jenkins-x/empty
  name: empty
  namespace: jx
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
