bases:
- ../environments.yaml
helmDefaults:
  atomic: true
  devel: false
  force: false
  recreatePods: false
  tillerless: false
  timeout: 520
  tls: false
  verify: false
  wait: true
releases:
- chart: stable/nginx-ingress
  name: nginx-ingress
  namespace: nginx
  values:
  - test_data/jenkins-x-versions/apps/stable/nginx-ingress/values.yaml.gotmpl
- chart: stable/velero
  name: velero
  namespace: velero
  values:
  - test_data/jenkins-x-versions/apps/stable/velero/values.yaml.gotmpl
  version: 2.7.4
- chart: stable/external-dns
  name: external-dns
  namespace: jx
  version: 2.15.3
- chart: bitnami/nexus
  name: nexus
  namespace: jx
  version: 9.2.1
- chart: jetstack/cert-manager
  name: cert-manager
  namespace: cert-manager
  version: v0.11.0
- chart: ../repositories
  name: repositories
  namespace: jx
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com