bases:
- ../environments.yaml
helmDefaults:
  atomic: true
  devel: false
  force: false
  recreatePods: false
  tillerless: false
  timeout: 520
  tls: false
  verify: false
  wait: true
releases:
- chart: zloeber/namespace
  name: namespace-cert-manager
  namespace: jx
  values:
  - generated/cert-manager/values.yaml
- chart: stable/external-dns
  name: external-dns
  namespace: jx
  values:
  - ../jx-requirements.values.yaml.gotmpl
  version: 2.15.3
- chart: bitnami/nexus
  name: nexus
  namespace: jx
  values:
  - ../jx-requirements.values.yaml.gotmpl
  version: 9.2.1
- chart: jetstack/cert-manager
  name: cert-manager
  namespace: cert-manager
  needs:
  - jx/namespace-cert-manager
  values:
  - ../jx-requirements.values.yaml.gotmpl
  version: v0.11.0
- chart: ../repositories
  name: repositories
  namespace: jx
  values:
  - ../jx-requirements.values.yaml.gotmpl
repositories:
- name: bitnami
  url: https://charts.bitnami.com/bitnami
- name: jetstack
  url: https://charts.jetstack.io
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: zloeber
  url: git+https://github.com/rawlingsj/helm-namespace@chart