bases:
- ../environments.yaml
helmDefaults:
  atomic: true
  devel: false
  force: false
  recreatePods: false
  tillerless: false
  timeout: 520
  tls: false
  verify: false
  wait: true
releases:
- chart: zloeber/namespace
  name: namespace-nginx
  namespace: jx
  values:
  - generated/nginx/values.yaml
- chart: zloeber/namespace
  name: namespace-velero
  namespace: jx
  values:
  - generated/velero/values.yaml
- chart: stable/nginx-ingress
  name: nginx-ingress
  namespace: nginx
  needs:
  - jx/namespace-nginx
  values:
  - test_data/jenkins-x-versions/apps/stable/nginx-ingress/values.yaml.gotmpl
  - ../jx-requirements.values.yaml.gotmpl
- chart: stable/velero
  name: velero
  namespace: velero
  needs:
  - jx/namespace-velero
  values:
  - test_data/jenkins-x-versions/apps/stable/velero/values.yaml.gotmpl
  - ../jx-requirements.values.yaml.gotmpl
  version: 2.7.4
repositories:
- name: stable
  url: https://kubernetes-charts.storage.googleapis.com
- name: zloeber
  url: git+https://github.com/rawlingsj/helm-namespace@chart