bases:
- ../environments.yaml
helmDefaults:
  atomic: true
  devel: false
  force: false
  recreatePods: false
  tillerless: false
  timeout: 520
  tls: false
  verify: false
  wait: true
releases:
- chart: jenkins-x/lighthouse
  force: true
  name: lighthouse
  recreatePods: true
  values:
  - ../jx-requirements.values.yaml.gotmpl
repositories:
- name: jenkins-x
  url: https://storage.googleapis.com/chartmuseum.jenkins-x.io